openapi: 3.0.0
info: 
  title: Classroom App
  description: basic app
  version: 0.1.9

servers:
  -url: http://localhost:3000/
    description: front-end
  -url: http://localhost:5000/
    description: back-end

paths:
  /users/getAllUsers:
    get: 
      summary: Returns users
      description: returns users
      responses:
        '200':
          description: Array of users
          content:
            application/json:
              schema:
                type: array
                items: 
                  type: string
        '404':
          description: Error
          