# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    name: running ci test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run tests
        run: |
          cd server
          npm install
          npm run test
    
      
  build:
    name: deploy in cloud
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
#         script: |
#                 cd code/FSD_GRP_26
#                 git pull origin master
#                 cd frontend
#                 npm run build
#                 mv build ../backend/build
#                 cd ..
#                 sudo docker-compose down
#                 sudo docker-compose up --build -d
#                 sudo systemctl restart nginx
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
